#!/bin/bash

echo "🚀 DESPLEGANDO CAMBIOS MANUALMENTE"
echo "================================="
echo ""
echo "Ya que el repositorio no existe, puedes desplegar los cambios manualmente:"
echo ""
echo "📋 OPCIÓN 1 - DESPLIEGUE MANUAL EN RENDER:"
echo "1. Ve a https://dashboard.render.com"
echo "2. Selecciona el servicio 'vitalmapeuti-back'"
echo "3. Ve a la pestaña 'Manual Deploy'"
echo "4. Haz clic en 'Deploy latest commit'"
echo ""
echo "📋 OPCIÓN 2 - CREAR REPOSITORIO Y DESPLEGAR:"
echo "1. Ve a https://github.com/new"
echo "2. Crea el repositorio 'vitalmapeuti'"
echo "3. Ejecuta estos comandos:"
echo "   git remote add origin https://github.com/cerezous/vitalmapeuti.git"
echo "   git push -u origin main"
echo "4. Render se desplegará automáticamente"
echo ""
echo "📋 OPCIÓN 3 - SUBIR ARCHIVOS MANUALMENTE:"
echo "Puedo crear un archivo ZIP con los cambios para que lo subas manualmente"
echo ""
echo "¿Cuál opción prefieres?"
