#!/bin/bash

echo "🔧 SOLUCIÓN DIRECTA PARA CREAR ADMINISTRADOR"
echo "============================================"
echo ""
echo "El problema es que los cambios no se han desplegado aún."
echo ""
echo "📋 SOLUCIONES INMEDIATAS:"
echo ""
echo "OPCIÓN 1 - DESPLEGAR CAMBIOS:"
echo "1. Ve a https://dashboard.render.com"
echo "2. Selecciona 'vitalmapeuti-back'"
echo "3. Ve a 'Manual Deploy'"
echo "4. Haz clic en 'Deploy latest commit'"
echo "5. Espera 2-3 minutos"
echo "6. Ejecuta el comando de actualización"
echo ""
echo "OPCIÓN 2 - USAR USUARIO EXISTENTE:"
echo "Por ahora usa 'mcerezo' / 'shualabn'"
echo "Aunque diga 'Enfermería', puedes usar el sistema"
echo ""
echo "OPCIÓN 3 - CREAR USUARIO ADMINISTRADOR MANUALMENTE:"
echo "1. Despliega los cambios primero"
echo "2. Ejecuta:"
echo "   curl -s -X POST https://vitalmapeuti-back.onrender.com/api/auth/register \\"
echo "     -H \"Content-Type: application/json\" \\"
echo "     -d '{\"nombres\":\"ADMIN\",\"apellidos\":\"SISTEMA\",\"estamento\":\"Administrador\",\"correo\":\"admin@vitalmape.com\",\"contraseña\":\"catita1008\"}'"
echo ""
echo "¿Cuál opción prefieres?"
