#!/bin/bash

echo "👑 ACTUALIZANDO USUARIO A ADMINISTRADOR"
echo "======================================"
echo ""
echo "Usuario: mcerezo"
echo "Nuevo estamento: Administrador"
echo ""
echo "📋 PASOS:"
echo ""
echo "1. DESPLEGAR CAMBIOS PRIMERO:"
echo "   - Ve a https://dashboard.render.com"
echo "   - Selecciona 'vitalmapeuti-back'"
echo "   - Ve a 'Manual Deploy'"
echo "   - Haz clic en 'Deploy latest commit'"
echo ""
echo "2. DESPUÉS DEL DESPLIEGUE, EJECUTA:"
echo "   curl -s -X PUT https://vitalmapeuti-back.onrender.com/api/auth/update-estamento \\"
echo "     -H \"Content-Type: application/json\" \\"
echo "     -d '{\"usuario\":\"mcerezo\",\"nuevoEstamento\":\"Administrador\"}'"
echo ""
echo "3. VERIFICAR LOGIN:"
echo "   curl -s -X POST https://vitalmapeuti-back.onrender.com/api/auth/login \\"
echo "     -H \"Content-Type: application/json\" \\"
echo "     -d '{\"usuario\":\"mcerezo\",\"contraseña\":\"shualabn\"}'"
echo ""
echo "✅ Después de esto, el usuario 'mcerezo' será Administrador"
