#!/bin/bash

echo "👑 CREANDO USUARIO ADMINISTRADOR"
echo "==============================="
echo ""
echo "Usuario: mcerezopr"
echo "Contraseña: catita1008"
echo "Email: mcerezopr@gmail.com"
echo "Estamento: Administrador"
echo ""
echo "📋 PASOS PARA CREAR EL ADMINISTRADOR:"
echo ""
echo "1. DESPLEGAR CAMBIOS PRIMERO:"
echo "   - Ve a https://dashboard.render.com"
echo "   - Selecciona 'vitalmapeuti-back'"
echo "   - Ve a 'Manual Deploy'"
echo "   - Haz clic en 'Deploy latest commit'"
echo ""
echo "2. DESPUÉS DEL DESPLIEGUE, EJECUTA:"
echo "   curl -s -X POST https://vitalmapeuti-back.onrender.com/api/auth/register \\"
echo "     -H \"Content-Type: application/json\" \\"
echo "     -d '{\"nombres\":\"MATIAS\",\"apellidos\":\"CEREZO PRADO\",\"estamento\":\"Administrador\",\"correo\":\"mcerezopr@gmail.com\",\"contraseña\":\"catita1008\"}'"
echo ""
echo "3. VERIFICAR LOGIN:"
echo "   curl -s -X POST https://vitalmapeuti-back.onrender.com/api/auth/login \\"
echo "     -H \"Content-Type: application/json\" \\"
echo "     -d '{\"usuario\":\"mcerezopr\",\"contraseña\":\"catita1008\"}'"
echo ""
echo "⚠️ IMPORTANTE: Después de crear el administrador, recuerda revertir el cambio"
echo "   que permite crear administradores desde el registro público."
