#!/bin/bash

echo "🚀 CREANDO REPOSITORIO EN GITHUB"
echo "==============================="
echo ""
echo "Para subir los cambios, necesitas crear un repositorio en GitHub:"
echo ""
echo "1. Ve a https://github.com/new"
echo "2. Nombre del repositorio: vitalmapeuti"
echo "3. Descripción: Sistema VitalMape UTI - Frontend y Backend"
echo "4. Marca como 'Public' o 'Private' (tu elección)"
echo "5. NO marques 'Add a README file'"
echo "6. NO marques 'Add .gitignore'"
echo "7. NO marques 'Choose a license'"
echo "8. Haz clic en 'Create repository'"
echo ""
echo "Después de crear el repositorio, ejecuta:"
echo "git remote add origin https://github.com/cerezous/vitalmapeuti.git"
echo "git push -u origin main"
echo ""
echo "O si prefieres, puedo ayudarte a crear el repositorio con un nombre diferente."
