#!/bin/bash

echo "🚀 DESPLEGANDO CAMBIOS EN RENDER - PASO A PASO"
echo "=============================================="
echo ""
echo "📋 PASOS PARA DESPLEGAR:"
echo ""
echo "1️⃣ ABRIR RENDER:"
echo "   👉 Ve a: https://dashboard.render.com"
echo ""
echo "2️⃣ SELECCIONAR SERVICIO:"
echo "   👉 Busca y haz clic en: 'vitalmapeuti-back'"
echo ""
echo "3️⃣ IR A MANUAL DEPLOY:"
echo "   👉 En el menú lateral, haz clic en: 'Manual Deploy'"
echo ""
echo "4️⃣ DESPLEGAR:"
echo "   👉 Haz clic en el botón: 'Deploy latest commit'"
echo ""
echo "5️⃣ ESPERAR:"
echo "   ⏳ Espera 2-3 minutos mientras se despliega"
echo "   📊 Verás el progreso en la pantalla"
echo ""
echo "6️⃣ VERIFICAR DESPLIEGUE:"
echo "   ✅ Cuando veas 'Deploy successful', los cambios están listos"
echo ""
echo "7️⃣ ACTUALIZAR USUARIO:"
echo "   🔄 Después del despliegue, ejecuta:"
echo "   curl -s -X PUT https://vitalmapeuti-back.onrender.com/api/auth/update-estamento \\"
echo "     -H \"Content-Type: application/json\" \\"
echo "     -d '{\"usuario\":\"mcerezo\",\"nuevoEstamento\":\"Administrador\"}'"
echo ""
echo "8️⃣ VERIFICAR LOGIN:"
echo "   🔍 Ejecuta:"
echo "   curl -s -X POST https://vitalmapeuti-back.onrender.com/api/auth/login \\"
echo "     -H \"Content-Type: application/json\" \\"
echo "     -d '{\"usuario\":\"mcerezo\",\"contraseña\":\"shualabn\"}'"
echo ""
echo "🎯 RESULTADO ESPERADO:"
echo "   ✅ El usuario 'mcerezo' aparecerá como 'Administrador'"
echo ""
echo "¿Ya estás en Render? ¡Empieza con el paso 1!"
