#!/bin/bash

echo "👑 SOLUCIÓN TEMPORAL PARA CREAR ADMINISTRADOR"
echo "============================================="
echo ""
echo "El usuario 'mcerezo' ya existe y funciona:"
echo "✅ Usuario: mcerezo"
echo "✅ Contraseña: shualabn"
echo "✅ Email: mcerezopr@gmail.com"
echo "✅ Estamento: Enfermería"
echo ""
echo "📋 OPCIONES:"
echo ""
echo "OPCIÓN 1 - USAR USUARIO EXISTENTE:"
echo "Puedes usar 'mcerezo' / 'shualabn' para acceder al sistema"
echo ""
echo "OPCIÓN 2 - CREAR ADMINISTRADOR:"
echo "1. Despliega los cambios primero:"
echo "   - Ve a https://dashboard.render.com"
echo "   - Selecciona 'vitalmapeuti-back'"
echo "   - Ve a 'Manual Deploy'"
echo "   - Haz clic en 'Deploy latest commit'"
echo ""
echo "2. Después del despliegue, ejecuta:"
echo "   curl -s -X POST https://vitalmapeuti-back.onrender.com/api/auth/register \\"
echo "     -H \"Content-Type: application/json\" \\"
echo "     -d '{\"nombres\":\"MATIAS\",\"apellidos\":\"CEREZO PRADO\",\"estamento\":\"Administrador\",\"correo\":\"admin@vitalmape.com\",\"contraseña\":\"catita1008\"}'"
echo ""
echo "3. Esto creará un usuario con nombre automático (ej: 'mcerezo' o 'mcerezo2')"
echo ""
echo "OPCIÓN 3 - CAMBIAR ESTAMENTO DEL USUARIO EXISTENTE:"
echo "Podemos modificar el usuario 'mcerezo' para que sea Administrador"
echo ""
echo "¿Cuál opción prefieres?"
